builds:
  - binary: supper
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - ldflags: -s -w -X "cmd.AppVersion={{.Env.GOVERSION}}"
archive:
  files:
    - web/*
    - web/static/**/*
