builds:
  - binary: supper
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - ldflags: -s -w -X "cmd.AppVersion={{.Env.GOVERSION}}"
archive:
  files:
    - web/*
    - web/static/**/*
nfpm:
  vendor: github.com/tympanix
  maintainer: tympanix <tympanix@gmail.com>
  description: Download subtitles in a breeze
  license: GNU-v3.0
  formats:
    - deb
  files:
    ./web/*: /var/lib/supper/
    ./web/static/**/*: /var/lib/supper/static
